[dependencies]
base = "https://github.com/dfinity/motoko-base#moc-0.7.4"
xtended-numbers = "https://github.com/edjcase/motoko_numbers#v1.0.2"

[package]
name = "cbor"
version = "0.1.3"
description = "A CBOR library for encoding and decoding CBOR bytes"
repository = "https://github.com/edjcase/motoko_cbor"