[package]
name = "ic-certification"
version = "0.1.3"
description = "Certification and Canister Signatures"
repository = "https://github.com/nomeata/ic-certification"

[dependencies]
sha2 = "0.0.3"
cbor = "0.1.3"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0"

