name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "install vessel"
        run: |
          mkdir /home/runner/bin
          echo "/home/runner/bin" >> $GITHUB_PATH
          wget --output-document /home/runner/bin/vessel https://github.com/dfinity/vessel/releases/download/v0.6.3/vessel-linux64
          chmod +x /home/runner/bin/vessel

      - name: Run Tests
        run: make test

      - name: Generate Docs
        run: make docs
