[package]
name = "ic-websocket-cdk"
version = "0.3.0"
description = "IC WebSocket Motoko CDK"
repository = "https://github.com/omnia-network/ic-websocket-cdk-mo"
keywords = ["ic", "websocket", "motoko", "cdk"]
license = "MIT"

[dependencies]
ic-certification = "0.1.3"
sha2 = "0.0.4"
cbor = "0.1.3"
base = "0.10.0"
